# Generated by Django 5.2.3 on 2025-06-28 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriaProducto',
            new_name='ProductoCategoria',
        ),
    ]
